### ISSUE TITLE
Expression in trigger 'Connection Status' gives false positives

### ISSUE THREAD

**Issue by luk4sk** [cavazquez/zabbix_template_apcupsd#1]
Hi
The expression in trigger "Connection Status in {{HOSTNAME}}"
`{apcupsd:apcupsd.status.regexp(ONLINE)}=0 or {apcupsd:apcupsd.status.regexp(ONLINE SLAVE)}=0`
doesn't work for me. I receive notifications even though the status value is equal to ONLINE.

I think, that better expression will be:
`{apcupsd:apcupsd.status.regexp(^ONLINE)}=0`
which covers both cases, status ONLINE and ONLINE SLAVE. At least it works for me.

**Comment by cavazquez** [comment]
![captura de pantalla de 2017-12-05 15-49-34](https://user-images.githubusercontent.com/4699299/33624706-fa12b970-d9d3-11e7-879a-8e4fc96fd844.png)
This work for me but your solution is better. Thanks.

**Comment by cavazquez** [comment]
Commit. 

"Change template: ONLINE and ONLINE SLAVE for ^ONLINE. Thanks luk4sk for your contribution"

**Comment by luk4sk** [comment]
Hi

The regular expression proposed by me is incorrect. It doesn't catch status ONLINE NOBATT (and maybe some others). Below is the right expression:

`{apcupsd:apcupsd.status.regexp(^ONLINE$|^ONLINE SLAVE$)}=0`

Sorry for the confusion...
